### ISSUE TITLE
MOR Functionality for SmartAgent

### ISSUE THREAD

**Issue by LachsBagel** [MorpheusAIs/moragents#30]
- converting ETH and staking into smart contract
- claim MOR rewards for code and capital
- bridge ETH to Arbitrum
- withdraw capital
- check MOR rewards 
- daily reward rate

**Comment by Bougey** [comment]
Thanks for adding this from the other thread!

**Comment by dorianjanezic** [comment]
Is anyone currently working on these enhancements?

I’d be happy to contribute by creating a PR to add the claim and rewards checking features. I’ve already implemented these in the community website, so I can adapt that work here as well.

Let me know if that sounds good, and I can get started right away.

**Comment by LachsBagel** [comment]
PR #48  seeks to address this. I'm working with author to move this past finish line.

**Comment by LachsBagel** [comment]
Focusing on just MOR claim and rewards check in PR #59
