### ISSUE TITLE
Move agent-specific routes to agent modules [Refactor]

### ISSUE THREAD

**Issue by danXyu** [MorpheusAIs/moragents#77]
- Wraps up the redesign from Flask to FastAPI. 
- Agent-specific routes should be moved to the appropriate agent modules, and then all of these routes should be imported and attached to the main FastAPI app. 
- Makes it so that every agent module contains all of the logic needed and none of that logic bleeds into the core server app.

**Comment by LachsBagel** [comment]
resolved
