### ISSUE TITLE
Crypto Arbitrage Agent [New Feature]

### ISSUE THREAD

**Issue by danXyu** [MorpheusAIs/moragents#86]
- Would be very cool if, when triggered / prompted, this agent could automatically scan all coins/tokens across various exchanges and identify any price discrepancies or potential arbitrage opportunities.
- The agent should be able to set up the transactions necessary to execute and take advantage of these arbitrage opportunities, but make sure to verify with the user before executing.

**Comment by sreefoundry** [comment]
Curious - what is the value proposition of manual searching?

Couldn't automated (non-AI) scripts listen for events and interact with DEX (or aggregator) endpoints?

**Comment by danXyu** [comment]
Some users might not be interested in arb functionality. The prompting could automatically limit the search to specific exchanges or tokens by pulling out those details with an LLM. 

Good point on setting this up as a background process though. We can introduce a notion of workflows / cron jobs to the app, functions like searching for arb opps that are scheduled to run on some interval and notifies the users whenever something actionable occurs.

**Comment by sreefoundry** [comment]
All of this could be achieved (less intensively) through exchange-specific API calls + CRON job

Moreover, arbitrage opportunities are time-bound and cannot be scheduled.

**Comment by danXyu** [comment]
I agree with that - don't you think being able to set up those exchange links + CRON jobs via an agent would be useful though?

**Comment by danXyu** [comment]
I'm gonna close this issue. I guess your point is why would the user want to configure this agent when this could just be set up automatically. 

After digging into this more crypto arb is also really hard, and inherently more rules based which doesn't make sense for an LLM.
